name: build-test
on:
  pull_request:
    branches:
      - main
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: install meson
        run: |
          python -m pip install meson>=1.7.2 ninja
      - name: Install ffmpeg
        run: sudo apt install -y ffmpeg libavcodec-dev libswscale-dev libavutil-dev libavformat-dev
      - name: Build
        run: |
          meson setup build
          meson compile -C build
