name: build-test
on:
  pull_request:
    branches:
      - main
  push:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: install meson
        run: |
          python -m pip install meson>=1.7.2 ninja
      - name: Install ffmpeg
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ffmpeg libavcodec-dev libswscale-dev libavutil-dev libavformat-dev gcc-14 g++-14
          version: 1.0
      - name: "Use GCC 14"
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 --slave /usr/bin/gcov gcov /usr/bin/gcov-14
          sudo update-alternatives --set gcc /usr/bin/gcc-14
      - name: Build
        run: |
          meson setup build
          meson compile -C build
  build-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: install meson
        run: |
          python -m pip install meson>=1.7.2 ninja
      - name: Install ffmpeg
        run: winget install "FFmpeg (Shared)" --disable-interactivity --accept-source-agreements
      - name: Build
        run: |
          meson setup build
          meson compile -C build
